### ISSUE TITLE
Error building with g++-4.9

### ISSUE THREAD

**Issue by issacnitin** [opencog/atomspace#454]
/home/catalyst/atomspace/opencog/rule-engine/forwardchainer/FCStat.cc:116:27: error: converting to ‘opencog::UnorderedHandleSet {aka std::unordered_set<opencog::Handle, opencog::handle_hash>}’ from initializer list would use explicit constructor ‘std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = opencog::Handle; _Hash = opencog::handle_hash; _Pred = std::equal_to<opencog::Handle>; _Alloc = std::allocator<opencog::Handle>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = opencog::handle_hash; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<opencog::Handle>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<opencog::Handle>]’
   UnorderedHandleSet all={};

Gcc, g++ version 4.9
Ubuntu version (uname -a) : Linux catalyst-HP-Pavilion-15-Notebook-PC 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by AmeBel** [comment]
confirmed. @misgeatgit any idea?

**Comment by williampma** [comment]
Why is `={}` even needed when an UnorderedHandleSet is already initialized empty?  Just remove that part.

**Comment by misgeatgit** [comment]
@williampma  Yes, thats one solution but I am trying to understand why this works on gcc 4.8 and not on 4.9 or above.

**Comment by ngeiswei** [comment]
Maybe 4.9 implements the C++11 standard more strictly (assuming that is covered in C++11 standard anyway).

**Comment by misgeatgit** [comment]
I compiled the code with g++ 4.8, 4.9 and 5 and the problem occurs only with version 4.9. I still don't know the exact reason though.Anyways I have sent the obvious fix for it.

**Comment by misgeatgit** [comment]
@issacnitin I hope the problem is solved.

**Comment by issacnitin** [comment]
Yes, thankyou :)
