### ISSUE TITLE
Can't find atomspace_api.h

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1669]
After cleaning my build folder and removing installed opencog includes and libs from my system I can no longer compile the atomspace. Getting the following error
```
[ 48%] Building CXX object opencog/cython/CMakeFiles/PythonEval.dir/PythonEval.cc.o
/home/nilg/OpenCog/atomspace/opencog/cython/PythonEval.cc:42:10: fatal error: opencog/atomspace_api.h: No such file or directory
 #include "opencog/atomspace_api.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by ngeiswei** [comment]
The bug has been introduced in 46783ef72
