### ISSUE TITLE
Support of gcc-4.9

### ISSUE THREAD

**Issue by kasimebrahim** [opencog/atomspace#1916]
I am having error building with g++-4.9. I might be able to solve this problem by editing some code but I was thinking of may be we should drop 4.9 support.
```
proto/ValueFactory.cc:25:43: error: cannot pass objects of non-trivially-copyable type ‘opencog::ProtoAtomPtr {aka class std::shared_ptr<opencog::ProtoAtom>}’ through ‘...’
         return (*cast_register[vtype])(ptr);
```

**Comment by ngeiswei** [comment]
I'm personally OK to drop gcc-4.9 support. Has anybody a problem with that?

**Comment by linas** [comment]
I guess we can drop gcc-4.9 support, but that specific bug showed up due to sloppy coding. I think I fixed it in #1918

**Comment by linas** [comment]
I mean to say, I think it will now compile with gcc-4.9, after #1918

**Comment by linas** [comment]
After the fix #1918, was the bug fixed?

**Comment by kasimebrahim** [comment]
No @linas it is still there 
<pre>
ValueFactory.h:101:31: error: cannot pass objects of non-trivially-copyable type ‘class std::vector<double>’ through ‘...’
             return (*fptr)(arg);

</pre>

**Comment by linas** [comment]
Hmm I don't ming dropping support for 4.9, but I'm just wondering why you are even testing it. Is this needed for some icog labs project?

Maybe the following will work, to fix this?
```
--- a/opencog/atoms/proto/ValueFactory.h
+++ b/opencog/atoms/proto/ValueFactory.h
@@ -67,7 +67,7 @@ public:
       * @throws invalid_argument exception.
       */
     template <typename TYP, typename ARG>
-    ProtoAtomPtr create(TYP vtype, ARG arg) const
+    ProtoAtomPtr create(TYP vtype, const ARG& arg) const
     {
         // Look up the factory only once; cache the result.
         static ValueFactory fptr = nullptr;
```

**Comment by Dagiopia** [comment]
I think the problem have to do with sending a vector object to the variadic ValueFactory function. It expects an array (c data) rather than objects. This should be an issue for value types float, string and link (excluding randomstream)

**Comment by Dagiopia** [comment]
abandoning the 4.9 seems like a better solution than rewriting the value factory though

**Comment by kasimebrahim** [comment]
@linas 

> but I'm just wondering why you are even testing it.

I thought I had to.
@Dagiopia 

> I think the problem have to do with sending a vector object to the variadic ValueFactory function

That is right we can't do that unless we specify the type

**Comment by linas** [comment]
OK, lets drop 4.9 then, it seems to be associated with ubuntu trusty, which is a few months away from end-f-life anyway.

**Comment by vsbogd** [comment]
I also think version from the Debian stable is a good choice.

**Comment by ngeiswei** [comment]
I think we can go with 6.3.0 and lower it down if we ever need to.

@kasimebrahim would you be OK to take care of it?

**Comment by ngeiswei** [comment]
Oh, @linas has already taken care of it ;-)

**Comment by ngeiswei** [comment]
Oh, actually only for the opencog repo, so if you @kasimebrahim have the chance to take care of it that's still welcome.

**Comment by kasimebrahim** [comment]
I will take care of it.

**Comment by linas** [comment]
Ubuntu xenial (16.04) has gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

it would be nice to set that as the minimum; I have maybe 6 containers with xenial, and would prefer not to have to upgrade them all just yet.

**Comment by linas** [comment]
```
   # IF (CMAKE_CXX_COMPILER_VERSION VERSION_LESS 5.4.0)
   #  MESSAGE(FATAL_ERROR "GCC version must be at least 5.4.0!")
   # ENDIF (CMAKE_CXX_COMPILER_VERSION VERSION_LESS 5.4.0)
```

**Comment by ngeiswei** [comment]
Cogutil and opencog have weird comments. cogutil recommends 5.4 (commented) and opencog recommends 6.3 (commented). But since it commented I'd say let's not bother for now. Thus I'm closing.
