### ISSUE TITLE
cython unit tests are failing

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#2737]
After the merge of pull req #2730 the `CythonAtomSpace` unit test started failing:

```
======================================================================
ERROR: test_add_link (test_atomspace.AtomSpaceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/linas/src/novamente/src/atomspace-git/tests/cython/atomspace/test_atomspace.py", line 73, in test_add_link
    l4 = Link(n1, n4, tv=TruthValue(0.5, 0.8))
TypeError: Link() got an unexpected keyword argument 'tv'

----------------------------------------------------------------------
Ran 77 tests in 6.407s
```

and
```
The following tests FAILED:
	153 - CythonAtomSpace (Failed)
```

**Comment by vsbogd** [comment]
@linas this test doesn't fail in CircleCI may be it is your local environment issue?

**Comment by linas** [comment]
it started passing at some point. Probably stale files somewhere in the build tree. 

I'm guessing that when cython pyx pxd files are changed, that the CMakefiles rebuild noly some of the needed files, but not all of them.  `rm -r` cython fixes the problem.
