### ISSUE TITLE
Protobuf causes build failure

### ISSUE THREAD

**Issue by glicerico** [opencog/atomspace#2139]
Atomspace doesn't compile in Ubuntu 18.04, complaining about protobuf. but I can build properly inside an Ubuntu 16.04 docker container.
Here's the error:

```
Scanning dependencies of target dist-gearman
[ 77%] Serializing with protobuf
Scanning dependencies of target persist
Scanning dependencies of target persist-sql
[libprotobuf WARNING google/protobuf/compiler/parser.cc:562] No syntax specified for the proto file: ZMQMessages.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defau
lted to proto2 syntax.)
Scanning dependencies of target exec
[ 77%] Building CXX object opencog/persist/guile/CMakeFiles/persist.dir/PersistSCM.cc.o
[ 77%] Building CXX object opencog/atoms/execution/CMakeFiles/exec.dir/ExecSCM.cc.o
Scanning dependencies of target zmqatoms
[ 77%] Building CXX object opencog/persist/gearman/CMakeFiles/dist-gearman.dir/DistSCM.cc.o
Scanning dependencies of target utilities_cython
[ 77%] Building CXX object opencog/persist/sql/multi-driver/CMakeFiles/persist-sql.dir/llapi.cc.o
[ 77%] Building CXX object opencog/persist/zmq/atomspace/CMakeFiles/zmqatoms.dir/ZMQMessages.pb.cc.o
[ 77%] Building CXX object opencog/cython/opencog/CMakeFiles/utilities_cython.dir/Utilities.cc.o
In file included from /home/andres/MyOpenCogSources/atomspace/build/opencog/persist/zmq/atomspace/ZMQMessages.pb.cc:4:0:
/home/andres/MyOpenCogSources/atomspace/build/opencog/persist/zmq/atomspace/ZMQMessages.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^~~~~
/home/andres/MyOpenCogSources/atomspace/build/opencog/persist/zmq/atomspace/ZMQMessages.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^~~~~
/home/andres/MyOpenCogSources/atomspace/build/opencog/persist/zmq/atomspace/ZMQMessages.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^~~~~
In file included from /home/andres/MyOpenCogSources/atomspace/build/opencog/persist/zmq/atomspace/ZMQMessages.pb.cc:4:0:
/home/andres/MyOpenCogSources/atomspace/build/opencog/persist/zmq/atomspace/ZMQMessages.pb.h:25:10: fatal error: google/protobuf/generated_message_table_driven.h: No such file or directory
 #include <google/protobuf/generated_message_table_driven.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
opencog/persist/zmq/atomspace/CMakeFiles/zmqatoms.dir/build.make:69: recipe for target 'opencog/persist/zmq/atomspace/CMakeFiles/zmqatoms.dir/ZMQMessages.pb.cc.o' failed
make[2]: *** [opencog/persist/zmq/atomspace/CMakeFiles/zmqatoms.dir/ZMQMessages.pb.cc.o] Error 1
CMakeFiles/Makefile2:1714: recipe for target 'opencog/persist/zmq/atomspace/CMakeFiles/zmqatoms.dir/all' failed
make[1]: *** [opencog/persist/zmq/atomspace/CMakeFiles/zmqatoms.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by glicerico** [comment]
As commented by @linas in https://github.com/opencog/atomspace/pull/2137 :
```But anyway, the short answer: the zmq/protobuf code is dead, obsolete, unmaintained. Just remove protobuf, that will disable the compile. The only reason that directory hasn't been completely trashed is that there's still some vague hope that someone will step up and do the work. But ... I dunno. If it causes build breaks, it should get trashed.```

@linas I am not familiar on how to "remove protobuf'. Does that mean removing every reference to it in the atomspace repo? Or something simpler like removing some flag in a Makefile?

**Comment by linas** [comment]
Well, read the error message. What does it say?
```
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
```

so, on you're ubuntu 18.04 system, you've got a version of protobuf installed that is *older* than your ubuntu 16.04 system.  Don't know how you did that.  Try `apt-get purge protobuff` ( or libprtobuf or golang-protof or whatever its called)You really do not need it for anything.

**Comment by linas** [comment]
Here:  https://en.wikipedia.org/wiki/Protocol_Buffers  -- its a library of stufff wrapped into some debian package.  Just remove that package, and then say `cmake ..; make`  The `cmake` will discover that you no longer have protobuf installed, and the it will skip compiling those parts of the atomspace that depend on of (the REST bindings)

**Comment by linas** [comment]
more generally, the correct long-term solution is to rip out the REST interfaces entirely. As a techniology, REST sucks. It should never have been picked in the first place.  The correct modern replacement for it would probably be GnuNet  https://en.wikipedia.org/wiki/GNUnet (although I'm a bit intoxicated by #scuttlebutt at the moment. but even ipfs and maidsafe or cjdns are plausible, but clearly have a much much higher barrier to usability)

**Comment by glicerico** [comment]
I would prefer not to remove the package, as it's apparently used by tensorflow (which I locally installed over the weekend, coincident when i started getting the problem in the atomspace). So, as a workaround I just commented out all references to protobuff and ZMQ in CMakeLists.txt in PR# https://github.com/opencog/atomspace/pull/2141

**Comment by linas** [comment]
A much simpler work-around would be to simply comment out `HAVE_PROTOBUF` in the cmakefiles for atomspace.

**Comment by glicerico** [comment]
@linas Thanks for the guidance... trying that now.

**Comment by Dagiopia** [comment]
this usually happens when you have the apt protobuf and you also build and install from source. Since the one from source would most likely have a higher version number, this problem occurs. Have you built protobuf from source? I'm wondering because you mentioned tensorflow and it needs a higher version of protobuf from the one on apt.

**Comment by glicerico** [comment]
Yes, my reading is that a different protobuf version was installed when I installed tensorflow

**Comment by Dagiopia** [comment]
Having both disrupts a lot. It's best to remove one of them. Maybe then the headers won't be generated by an older version in the first place.

**Comment by linas** [comment]
Closing, seems like this was resolved, right?
